[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
paper_trading = "b6NjCktqaB4KqTvsNmYTJ9KBfwMJ7Sh4hMJ2Xz26YR3"

[programs."https://rpc.magicblock.app/devnet/"]
close-position = "CXnKyp5DGMWRHsj9JsbECqBbDP1GeUF3c8AYSPZMmNb2"
competition = "FPKpeKHnfYuYo8JDiDW7mNzZB8qgf1mLYwpQAcbGyVhJ"
join-competition = "5aJzg88rRLAFGN1imRwK84WMD4JyZBvz7n47nSQz9oGm"
leaderboard = "BCrmcoi7dEgg7UY3SpZfM4dihAWaYuNk3wprXsy1Xp5X"
open-position = "GdWvbNgbNxWHbSDTBweSi9zPgtRhggGxaJsCxL5vwDp9"
position = "9ACLRxNoDHXpHugLUmDtBGTQ6Q5vwnD4wUVSaWaNaVbv"
settle-competition = "32S5nHLK93PNVJQZgd4PQY4v9tkiLU2j9bEbHhJN4CuL"
trading-account = "3PDo9AKeLhU6hcUC7gft3PKQuotH4624mcevqdSiyTPS"

[programs.localnet]
paper_trading = "b6NjCktqaB4KqTvsNmYTJ9KBfwMJ7Sh4hMJ2Xz26YR3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.magicblock.app/devnet/"
wallet = "~/.config/solana/id.json"

[workspace]
members = []

[scripts]
executor = "ts-node tests/executor.ts"
initialise = "ts-node tests/initialise.ts"
test = "sleep 5 && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899
